# Generated by Django 2.2 on 2021-02-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='название')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='recipes/', verbose_name='Изображение')),
                ('recipe_text', models.TextField(verbose_name='рецепт')),
                ('ingredients', models.TextField(max_length=500, null=True, verbose_name='ингредиенты')),
                ('time_for_cooking', models.TextField(verbose_name='время приготовления')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
