# Generated by Django 2.2 on 2021-04-10 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210410_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_for_cooking',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Так быстро не готовит даже Флэш')], verbose_name='время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(1, 'Значение должно быть больше нуля')]),
        ),
    ]
