# Generated by Django 2.2 on 2021-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210419_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.TextField(max_length=150, verbose_name='наименование ингредиента'),
        ),
    ]
