# Generated by Django 2.2 on 2021-04-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210419_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=150, verbose_name='наименование ингредиента'),
        ),
    ]
